apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCRENDQWV5Z0F3SUJBZ0lKQU1SaDMwQVQzOURHTUEwR0NTcUdTSWIzRFFFQkN3VUFNQmN4RlRBVEJnTlYKQkFNTURERXdMakUxTWk0eE9ETXVNVEFlRncweE9URXdNVFF4T1RFME1ETmFGdzAwTnpBek1ERXhPVEUwTUROYQpNQmN4RlRBVEJnTlZCQU1NRERFd0xqRTFNaTR4T0RNdU1UQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQCkFEQ0NBUW9DZ2dFQkFNSWd4MXBSVVBQQ0ZzN0NyNDl1bkFCR0owRFlZZ0kwaEh4RHdIajVyOWgwQlhTdXpLMDAKNFlzZnRnWWhQWjhSOGZGU29sSVlWblNMdG55TFRVVFVBYVZvTHJJSVc0enYyTFdPclZUSXhTdXVKMGV2QmxDYQpHd0dxWFg2RkNwVllyd0ZNSGVZQ2lrZWNOMWZwYzJUdWhsODJsZVJtU09KSlhtYk1OZlJmaUJyZ0FqdUtxeGJoClJrR1pSYWxhcWdGYmJtZ1ZFZjBIdnZYWGo0dGFNc08yT0VWdDlMRlFJS0gzaG4vMHU2YjMwNzkwNmJHc0l5Z1kKVzhEa0lJUTRPbzg0RTQxeitYRUZwdVY3cDUwRmFLYTdHZ3dMc1hqeFA0SnByWXdwcll6NDU1Q2FNeS85MThZMApUdTZGcTl6c2NWdHcxTUxaRWNQdHIxWUY3Z1dHbGFDZkYxRUNBd0VBQWFOVE1GRXdIUVlEVlIwT0JCWUVGTERWCkZ6aml5RVdGK1M0NEU3dHF5YVRRaUJkd01COEdBMVVkSXdRWU1CYUFGTERWRnpqaXlFV0YrUzQ0RTd0cXlhVFEKaUJkd01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFKT0FRT0poSUlNVwo2WDE2a3JxR2pVOStVRjFLYmRobitXRUVJTUZuV1VQdGVDVExkYUt1L3RhUHZOTXhtQk13SGhYVVhoQUFSNkNLCmU1akJvTWozdDgvb3YyeVFZYVo5cUIrSlRpSG05TDNBbDlpcFl1QjZ3ajd4ODdRSmZic2dleWhnald5ZzNielkKV2w2OEdNTXplbUdlaUVBaEJGK3ZBUmxRMFpNZ0FqUnREMGZNdlM4RDQxNlBDaVdPakk0bjhwODZYL1R6VlVwLwpzK3Y2UkZNTGdodHNIb21pUjQyRTlTL0NkcWc4blUxS2RJTnNJeGZtS0kzQjhocndEaU5rcHdrUnluSmNIQU04CjFZUldEeUxLUU1CVXVhaDFLWGg0dUUrK1M3NUFzdCttSVhCKy9sbFlkZEZleEVDZCtMNE4rczEyUDJQc0w2MUMKUnN4T08wS1ZPazg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://51.254.35.46:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    username: admin
    password: aCtyL0dKalJhUE1FYWhtNnFIajdiMHowdVpBanc4dWRRZzdsNkNkN21Kbz0K
